import Head from 'next/head';
import Layout from '../layouts/Layout';
import NavigationBar from '../layouts/NavigationBar';
import Footer from '../layouts/Footer';
import { Spacer } from '@nextui-org/react';
import Password from '../containers/Password';
import PasswordControls from '../containers/PasswordControls';
import InformationCard from '../components/InformationCard';
import { Text } from '@nextui-org/react';

const spacing = 1.5;

export default function Home() {
	return (
		<>
			<Layout>
				<Head>
					<title>psswrdgnrtr</title>
					<meta name='description' content='Generated by create next app' />
					<meta name='viewport' content='width=device-width, initial-scale=1' />
					<meta name='author' content='John Rommel Octaviano' />
					<meta
						name='description'
						content='Generate and utilize robust passwords for different transactions online.'
					/>
					<meta name='designer' content='John Rommel Octaviano' />
					<meta name='reply-to' content='johnrommel.octaviano@gmail.com' />
					<meta name='owner' content='John Rommel P. Octaviano' />
					<meta name='summary' content='John Rommel Octaviano' />
					<meta name='directory' content='submission' />
					<meta name='coverage' content='Worldwide' />
					<meta name='distribution' content='Global' />
					<meta
						name='subject'
						content='John Rommel Octaviano, Random Password Generator, Password Generator, Password, Generator'
					/>
					<meta
						name='keywords'
						content='John Rommel Octaviano, Random Password Generator, Password Generator, Password, Generator'
					/>
					<meta name='topic' content='Password Generator' />
					<meta name='category' content='Security' />
					<meta name='target' content='all' />
					<meta name='audience' content='all' />
					<meta name='rating' content='General' />
					<meta
						name='generator'
						content='Visual Studio Code, XD, Photoshop, Firefox Developer Edition, Windows Terminal, etc.'
					/>
					<meta name='referrer' content='no-referrer' />
					<meta name='fragment' content='!' />
					<meta
						name='format-detection'
						content='telephone=no,date=no,address=no,email=no,url=no'
					/>
					<meta name='mssmarttagspreventparsing' content='true' />
					<meta name='HandheldFriendly' content='True' />
					<meta name='robots' content='index,follow' />
					<meta name='googlebot' content='index,follow' />
					<meta name='google' content='nositelinkssearchbox' />
					<meta name='slurp' content='noydir' />
					<meta http-equiv='Window-Target' content='_top' />
					<meta http-equiv='Pragma' content='no-cache' />
					<meta http-equive='expires' content='-1' />
					<meta
						http-equiv='Page-Enter'
						content='RevealTrans(Duration=1.0,Transition=1)'
					/>
					<meta
						http-equiv='Page-Exit'
						content='RevealTrans(Duration=1.0,Transition=1)'
					/>
					<meta name='msapplication-navbutton-color' content='#0072F5' />
					<meta http-equiv='imagetoolbar' content='no' />
					<meta name='ICBM' content='14.169648, 121.333653' />
					<meta name='geo.position' content='14.169648;121.333653' />
					<meta name='geo.region' content='PH-LAG' />
					<link
						rel='author'
						href='data:text/plain;base64,VGhpcyBwZXJzb25hbCBwb3J0Zm9saW8gaXMgYnVpbHQgYnkgSm9obiBSb21tZWwgT2N0YXZpYW5vLCBhIEZyb250IEVuZCBEZXZlbG9wZXIsIFVzZXIgSW50ZXJmYWNlIERlc2lnbmVyLCBHcmFwaGljIERlc2lnbmVyLCBhbmQgVGVjaG5pY2FsIEJsb2dnZXIgYmFzZWQgaW4gdGhlIFBoaWxpcHBpbmVzLg0KDQpGYWJyaWNhdGluZyB0aGluZ3MgaXMgYSB0aW1lbGVzcyBqb3VybmV5LiBBIG1hZ25pZmljZW50IHZveWFnZSB0aGF0IGxlYWRzIHRvIHRoZSBwYXRoIG9mIHBvc3NpYmlsaXRpZXMuIENvbnRpbnVpbmcgb24gdG8gdGhlIHByb2xvbmdlZCBlbmQu'
					/>
					<link rel='me' href='mailto:johnrommel.octaviano@gmail.com' />
					<link rel='me' href='sms:+639562057280' />
					<link
						rel='icon'
						sizes='192x192'
						href='https://img.icons8.com/ios/100/null/engine.png'
					/>
					<link
						rel='mask-icon'
						href='https://img.icons8.com/ios/100/null/engine.png'
						color=''
					/>
					<meta name='apple-mobile-web-app-capable' content='yes' />
					<meta
						name='apple-mobile-web-app-status-bar-style'
						content='black-translucent'
					/>
					<meta
						name='apple-mobile-web-app-title'
						content='John Rommel Octaviano'
					/>
					<meta name='apple-mobile-web-app-capable' content='yes' />
					<meta name='apple-mobile-web-app-status-bar-style' content='black' />
				</Head>
				<NavigationBar />
				<Spacer y={spacing} />
				<main>
					<InformationCard
						content={
							<Text
								h2
								css={{
									textAlign: 'center',
								}}
							>
								Generate and utilize robust passwords for different transactions
								online.
							</Text>
						}
					/>
					<Spacer y={spacing} />
					<Password />
					<Spacer y={spacing} />
					<InformationCard
						content={
							<Text
								css={{
									textAlign: 'center',
								}}
							>
								Use the slider below to determine the desired length of the
								password to be generated. Also, use the different checkboxes to
								choose the desired content of the actual password.
							</Text>
						}
					/>
					<Spacer y={spacing} />
					<PasswordControls />
				</main>
				<Spacer y={spacing} />
				<Footer />
				<Spacer y={spacing} />
			</Layout>
		</>
	);
}
